<!DOCTYPE html PUBLIC "-//WAPFORUM//DTD XHTML Mobile 1.0//EN" "http://www.wapforum.org/DTD/xhtml-mobile10.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" /> 
    <meta name="apple-mobile-web-app-capable" content="yes" />
    <meta name="apple-mobile-web-app-status-bar-style" content="black" />
    <meta content="telephone=no" name="format-detection" /> 
    <meta content="width=device-width,target-densitydpi=high-dpi, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
    
    <title>聊天</title>
    <link href="/static/wap/css/index.css" rel="stylesheet" />  
    <script type="text/javascript">
       var IM = {};
        IM.data = {
            IMrand : '{{IMrand}}',
            IMtoken :  '{{IMtoken}}',
    	    roomid : '{{roomid}}',
    	    user : {"uid":"{{user['uid']}}","nickname":"{{user['nickname']}}","face":"{*user['face']*}","sex":"{{user['sex']}}"} ,
            oldmessage: {}, 
    	    socket : 'ws://m.iepush.com/test/websocket?token=1234567&roomid=1000'
    	}
    </script>
</head>

<body class="body" ondblclick="return false;"> 
    <header class="topNav"> 
         <!-- <a style="float:left;" class="fl navBtn" href="/index/index">首页</a>-->
        <h1 class="title">&nbsp;{{roomname}}</h1>
        <!--  <a style="float:right;" class="fr navBtn" href="/login/logout">退出</a>-->
    </header>
    
    <div class="main">   
        <div id="chatArea" class="box chat">   
            <div id="messageList" style="padding:10px 10px 0; overflow-y:auto;  overflow-x: hidden;  flex: 1;  ">  
                        
            </div>   
        </div>   
    </div>  
    
    <footer class="footer">  
        <div id="face_box" class="face_box hide">
            <ul class="exp_hd">  
                <li class="exp_hd_item active" data-i="0">  
                    <a href="javascript:;">QQ表情</a>  
                </li>  
                <li class="exp_hd_item" data-i="1">  
                    <a href="javascript:;">图片</a>  
                </li>  
                <li class="exp_hd_item" data-i="2">  
                    <a href="javascript:;">语音</a>  
                </li>  
            </ul>  
            
            <div class="exp_bd">    
                 <div id="face_box_qq" class="exp_cont active"> 
					<a title="微笑" type="qq" class="qqface qqface0"><img src="/static/wap/img/qq/100.png" /></a> 
					<a title="撇嘴" type="qq" class="qqface qqface1"><img src="/static/wap/img/qq/101.png" /></a> 
					<a title="色" type="qq" class="qqface qqface2"><img src="/static/wap/img/qq/102.png" /></a> 
					<a title="发呆" type="qq" class="qqface qqface3"><img src="/static/wap/img/qq/103.png" /></a>
					<a title="得意" type="qq" class="qqface qqface4"><img src="/static/wap/img/qq/104.png" /></a> 
					<a title="害羞"  type="qq" class="qqface qqface5"><img src="/static/wap/img/qq/105.png" /></a> 
					<a title="尴尬"  type="qq" class="qqface qqface5"><img src="/static/wap/img/qq/106.png" /></a>  
					<a title="调皮"  type="qq" class="qqface qqface6"><img src="/static/wap/img/qq/107.png" /></a>  
				    <a title="呲牙"  type="qq" class="qqface qqface7"><img src="/static/wap/img/qq/108.png" /></a>
				    <a title="惊讶" type="qq" class="qqface qqface8"><img src="/static/wap/img/qq/109.png" /></a>
				    <a title="酷" type="qq" class="qqface qqface9"><img src="/static/wap/img/qq/110.png" /></a> 
			        <a title = "冷汗"  type="qq" class="qqface qqface10"><img src="/static/wap/img/qq/111.png" /></a>  
				    <a title="偷笑"  type="qq" class="qqface qqface11"><img src="/static/wap/img/qq/112.png" /></a>
				    <a title="白眼"  type="qq" class="qqface qqface12"><img src="/static/wap/img/qq/113.png" /></a> 
				 </div> 
				  
                <div id="face_box_pic"  class="exp_cont emoji_face">
                    <a style=" border: 1px solid rgb(61, 127, 222); height: 34px; border-radius: 3px; color: rgb(61, 127, 222); display: inline-block; line-height: 34px; margin-left: 15px; text-align: center; width: 110px; position: relative;" >   
                        上传图片                
                        <input id="face_box_pic_file" type="file" 
                           style="width: 110px;opacity: 0;position: absolute;left: 0px;top: 0px;cursor: pointer;height: 100%;" 
                           url='/upload/file'
                           path="Filedata" 
                           name="Filedata" 
                         >
                    </a> 
                </div>  
                
                <div id="face_box_audio"  class="exp_cont tuzki_face"> 
                    <a style="border: 1px solid rgb(61, 127, 222); height: 34px; border-radius: 3px; color: rgb(61, 127, 222); display: inline-block; line-height: 34px; margin-left: 15px; text-align: center; width: 110px; position: relative;" >  
                        语音录制 
                         <input id="face_box_audio_file"  type="file" 
                           style="width: 110px;opacity: 0;position: absolute;left: 0px;top: 0px;cursor: pointer;height: 100%;"
                           path='Filedata' 
                           url='/upload/file' 
                           name="Filedata">
                    </a> 
                </div>
           </div>
        </div>  
        
        <div class="box_ft_hd">  
            <div class="eaitWrap">  
                <pre id="editArea" class="editArea" contenteditable="true"></pre>  
            </div>  
            <button href="javascript:;" class="web_wechat_face" id="web_wechat_face">工具</button>   
            <button href="javascript:;" class="web_wechat_btn" id="btn_send">发送</button>  
        </div>  
    </footer> 
    <script src="/static/wap/js/jquery.min.js"  type="text/javascript"></script>  
    <script src="/static/wap/js/ajaxfileupload.js"  type="text/javascript"></script>  
    <script src="/static/wap/js/im.js?442236as13"  type="text/javascript"></script>   
</body>  
</html>  
