<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no' />
<link type="text/css" rel="stylesheet" href="/static/wap/css/public.css"/>
<link type="text/css" rel="stylesheet" href="/static/wap/css/main.css?07201"/>
<title>好友列表</title>
<script src="/static/wap/js/jquery.min.js"  type="text/javascript"></script> 
<script src="/static/wap/js/ajaxfileupload.js"  type="text/javascript"></script>  
</head>
<style>
  .body .topNav {
	 background-color: #486590;
    color: #fff;
    height: 2rem;
    line-height: 2rem;
    text-align: center;
}

.body header.topNav .title{
	   display: inline-block;
    font-size: 0.8rem;
    margin: auto;
}
.body header.topNav .navBtn{
	 background-color: #6582ac;
    border-radius: 0.1rem;
    color: #fff;
    height: 1.25rem;
    line-height: 1.25rem;
    margin: 8px 18px 0;
    text-align: center;
    width: 3.325rem;
}
    
  .member .box ul li {
	   border-bottom: 1px solid #ececec;
    display: block;
    height: 50px;
    line-height: 50px;
    padding: 0 10px;
  }
 .member .box ul li input{  width: 50%;}
  .paging{
   background-color: #486590;
    color: #fff;
    height: 2rem;
    line-height: 2rem;
    margin-top: 0.4rem;
    text-align: center;
  }
  .paging a{ 
    border-radius: 0.1rem;
    color: #fff;
    height: 1.25rem;
    line-height: 1.25rem;
    margin: 8px 18px 0;
    text-align: center;
    width: 3.325rem;
  }
  .paging  .curr{ 
    background-color: #000045;
   }
</style> 
<body class="body"> 
        <header class="topNav">
            <a class="fl navBtn" href="/auth/logout">退出</a>
            <h1 class="title">首页</h1>
            <a class="fr navBtn" href="/user/info">用户中心</a>
        </header>
 
       <div class="member"> 
          <div class="box">
                <ul> 
                    <li onclick="window.location.href='/user/list'"> 
                          <div style="float:left;"><img src="/static/wap/img/portrait.jpg" alt="头像" style="width:50px;height:50px;"> </div> 
                          <div><a href="/user/list"> 用户列表 </a></div>  
                    </li>
                    
                    <li onclick="window.location.href='/im/room'"> 
                          <div style="float:left;"><img src="/static/wap/img/portrait.jpg" alt="头像" style="width:50px;height:50px;"> </div> 
                          <div><a href="/im/room"> 讨论群 </a></div>  
                    </li>
                      
                 </ul>    
           </div> 
       </div>   
    </body>
</html> 
 