<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no' />
<link type="text/css" rel="stylesheet" href="/static/wap/css/public.css"/>
<link type="text/css" rel="stylesheet" href="/static/wap/css/main.css?07201"/>
<title>个人中心</title>
<script src="/static/wap/js/jquery.min.js"  type="text/javascript"></script> 
<script src="/static/wap/js/ajaxfileupload.js"  type="text/javascript"></script>  
</head>
<style> 
  .body .topNav {
	 background-color: #486590;
    color: #fff;
    height: 2rem;
    line-height: 2rem;
    text-align: center;
}

.body header.topNav .title{
	   display: inline-block;
    font-size: 0.8rem;
    margin: auto;
}
.body header.topNav .navBtn{
	 background-color: #6582ac;
    border-radius: 0.1rem;
    color: #fff;
    height: 1.25rem;
    line-height: 1.25rem;
    margin: 8px 18px 0;
    text-align: center;
    width: 3.325rem;
}

.member .box ul li {
	   border-bottom: 1px solid #ececec;
    display: block;
    height: 50px;
    line-height: 50px;
    padding: 0 10px;
  }
 .member .box ul li input{  width: 50%;}
</style>
<body class="body">
        <header class="topNav"> 
            <h1 class="title">个人中心</h1>
            <!-- 
            <a class="fr navBtn"  ></a>
             -->
        </header>
            
        <div class="member">
             <form id="myform" method="get">
                 <div class="box">
                    <ul>
                        <li><span>手机号：</span> 
                            <input type="text" placeholder="手机号码" id="mobile" maxlength="11" disabled="disabled" 
                               name="mobile" class="text" value="{{userinfo['mobile']}}"/>
                        </li>
                         
                        <li>
                            <span>密    码: </span> 
                            <input type="password" name="password" id="password"  placeholder="密码(不填不修改)" class="text"  value="" maxlength="20" />
                        </li> 
                         
                         <li> <span>真实名：</span> 
                              <input type="text" placeholder="姓名" id="realname" maxlength="20" name="realname"  value="{{userinfo['realname']}}" class="text"/> 
                         </li> 
                        
                          <li> <span>昵    称：</span> 
                               <input type="text" placeholder="昵称" id="nickname" maxlength="20" name="nickname"  value="{{userinfo['nickname']}}" class="text"/> 
                         </li> 
                        
                         <li style="width: 50%;">    
                                 <span>性    别:</span>
                                 <select name="sex" id="sex_id">
                                      <option 
                                        {% if userinfo['sex'] == 1 then %}
                                           selected = "selected"
                                        {% end %}  value="1">男</option>
                                      <option 
                                         {% if userinfo['sex'] == 2 then %}
                                           selected = "selected"
                                        {% end %} 
                                      value="2">女</option>
                                      <option 
                                        {% if userinfo['sex'] == 3 then %}
                                           selected = "selected"
                                        {% end %} 
                                      value="3">妖</option>
                                 </select>  
 
                         </li>
                          
                         <li style="width: 50%;"> <span>头    像: </span> 
                                  <a style="  border: 1px solid rgb(61, 127, 222);
                                                height: 34px;
                                                border-radius: 3px;
                                                color: rgb(61, 127, 222);
                                                display: inline-block;
                                                line-height: 34px;
                                                margin-left: 15px;
                                                text-align: center;
                                                /* width: 110px;*/
                                                position: relative;                                                            
                                               " >   
                                           上传图片                
                                              <input id="face_box_pic_file" type="file" 
                                                               style="/* width: 110px;*/opacity: 0;position: absolute;left: 0px;top: 0px;cursor: pointer;height: 100%;" 
                                                               url='/upload/face'
                                                               path="Filedata" 
                                                               name="Filedata" >
                                 </a> 
                                 <div id="myface"  style="float:right; width:50px;height:50px;"> 
                                 
                                        {% if userinfo['face'] then %}
                                            
                                     
                                         <img id="myface_img" style=" width:50px;height:50px;" alt="当前头像" src="{{userinfo['face']}}">
                                         <input id="myface_input"  type="hidden" name="face" value="{{userinfo['face']}}"/> 
                                         
                                        {% else %} 
                                   
                                         <img id="myface_img"   style=" width:50px;height:50px;" alt="当前头像" src="/static/wap/img/portrait.jpg">
                                         <input id="myface_input"  style=" width:50px;height:50px;" type="hidden" name="face" value="/static/wap/img/portrait.jpg"/> 
                                       {% end %} 
                                 </div>
                         </li> 
                    </ul>  
                </div>
                
                 <div class="cr"></div>
                 <span id="doreg" class="submit">提交</span>
            
            </form>
            
           <div class="clear"></div>
        </div>

<script type="text/javascript">


var User = {
    flag : true,
    init : function() {
        var self = this;
        $('#doreg').click(function(){   
            self.info();
        });
  
        //图片上传
        $('#face_box_pic_file').live("change", function () {
        	  self.upload.on(this); 
        	  $('#face_box_pic_file').replaceWith($('#face_box_pic_file').clone(true)); 
        });
    },
    upload:{
		 on : function (dom){
		       var self = this;
	    	   var mark = arguments[1] != undefined ? arguments[1] : null;
    	        if (typeof(User.upload.start) == 'function') {
    	        	self.start(dom, mark);
    	        }
	    	        
    	    	$.ajaxFileUpload({
    	    		url : $(dom).attr('url'),
    	            data : {},//{'path' : $(dom).attr('path'), 'crop' : '其他字段', 'compress' : '其他字段'},
    	    		secureuri : false,
    	    		fileElementId : $(dom),
    	    		dataType: 'json',
    	            success : function(data) { 
    	                if (data.success) {//成功  
    	                	self.success(data); 
    	                } else {
    	                	self.feild(data);   //失败
    	                }
    	            }
    	    	})
    	    	return false; 
	       },
	       start: function (dom, mark){
	    	    //console.log('上传即将开始');
	       },
	       success: function(data){   //上传成功  
		        
	    	    $('#myface_input').val(data['filename']);  
	    	    $('#myface_img').attr('src', data['filename']);
	       },
	       feild :function(data){
	    	    console.log('上传失败 ');
	    	   console.log(data);
	    	   //上传失败 
	       }
	 },
    info : function() {
        var self = this;   
        var data = {},password,nickname,realname,sex,face;  
          data['password'] = password = $("#password").val(); 
          data['nickname'] = nickname = $("#nickname").val();
          data['realname'] = realname = $("#realname").val();  
          data['sex']      = sex = $('#sex_id').val(); 
          data['face']     = face = $("#myface_input").val();  
        if ('' == realname)
        {
             self.alert('请输入姓名');
             return;
        }
        
        if (!self.flag)
        {
            return;
        }
        self.flag = false;  
        $.post('/user/info', data, function(res) {
            self.flag = true;
            console.log(res);
            if (res.success)
            {
                  location.href = "/index"; 
                 return false;
            }
             self.alert(res.msg);
        }, 'JSON');
    },
    alert : function(msg) {
        var domsg = $("#domsg"); 
        if (domsg.length < 1)
        {
            domsg = document.createElement("div");
            domsg.id = "domsg";
            domsg.className = "popupWindow";
            var string = '<div class="hint"><div class="text" id="msgtext" style="padding: 20px 0;" >'+ msg +'</div>';
            string += '<div class="btnBox"><a class="btnStyle btn01" id="doconfig" style="width: 100%;" >确定</a>';
            string += '</div></div>';
            domsg.innerHTML = string;           
            document.body.appendChild(domsg);
            
            $("#doconfig").click(function() {
                $("#domsg").css("display","none"); 
            });
        }
        $("#domsg").css("display","block");  
        $("#msgtext").html(msg);
    }
};

User.init();
</script>

</body>
</html>

