<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name='viewport' content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no' />
<link type="text/css" rel="stylesheet" href="/static/wap/css/public.css"/>
<link type="text/css" rel="stylesheet" href="/static/wap/css/main.css?07201"/>
<title>好友列表</title>
  
</head>
<style>
  .body .topNav {
	 background-color: #486590;
    color: #fff;
    height: 2rem;
    line-height: 2rem;
    text-align: center;
}

.body header.topNav .title{
	   display: inline-block;
    font-size: 0.8rem;
    margin: auto;
}
.body header.topNav .navBtn{
	 background-color: #6582ac;
    border-radius: 0.1rem;
    color: #fff;
    height: 1.25rem;
    line-height: 1.25rem;
    margin: 8px 18px 0;
    text-align: center;
    width: 3.325rem;
}
    
  .member .box ul li {
	   border-bottom: 1px solid #ececec;
    display: block;
    height: 50px;
    line-height: 50px;
    padding: 0 10px;
  }
 .member .box ul li input{  width: 50%;}
  .paging{
   background-color: #486590;
    color: #fff;
    height: 2rem;
    line-height: 2rem;
    margin-top: 0.4rem;
    text-align: center;
  }
  .paging a{ 
    border-radius: 0.1rem;
    color: #fff;
    height: 1.25rem;
    line-height: 1.25rem;
    margin: 8px 18px 0;
    text-align: center;
    width: 3.325rem;
  }
  .paging  .curr{ 
    background-color: #000045;
   }
</style> 
<body class="body"> 
        <header class="topNav" onclick="window.location.href='/';">  
            <h1 class="title">用户列表</h1> 
        </header>
 
       <div class="member"> 
           <ul> 
            	{% if userall then %}
	                 {% for _, v in pairs(userall) do %}  
	                    
	                    <li style="line-height: 1.5rem; overflow: hidden;"> 
                              <div style="float: left; width:50px;"><img   alt="头像" src="/static/wap/img/portrait.jpg"> </div> 
                              <div style="float:right;"><a href="##">{{v['uid']}} -- {{v['nickname']}} </a></div>  
                        </li>
                      
	                  {% end %}
	             {% end %}
             
           </ul>    
       
       </div> 
       
		{% if page then %}
              <div class="paging">
    			  <a href="{{page['home']}}">首页</a>
    			    {% if page['prev'] then %}
    			      <a href="{{page['prev']}}"> 上一页</a>
    			    {%else%}
    			      <a href="javascript:;">上一页</a> 
    			    {% end %}
    			     
    			   {% if page['num'] then %}
    			       {% for k, v in pairs(page['num']) do %}  
    				       
    				          {% if  page['page'] == k then %} 
    	                     	<a href="{{v}}"   class="curr" >{{k}}</a>  
    	                      {%else%}
    	                     	<a href="{{v}}" >{{k}}</a>  
    	                      {% end %} 
    				   {% end %}
    				{%end%} 
    				   
    				{% if page['next'] then %}
    			          <a href="{{page['next']}}">下一页</a>
    				{%else%}
    				      <a href="javascript:;">下一页</a> 
    				{% end %} 
    				    
    				<a href="{{page['end']}}">末页</a>
    		   </div>  
    	{% end %} 
    </body>
</html> 
 
